version: "3.8"

services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: job_market
      POSTGRES_PASSWORD: job_market
      POSTGRES_DB: job_market
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: